name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x to Build

      - name: Install node_modules
        run: npm install

      - name: Connect to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          run: |
            cd /home/ubuntu/project/CI-CD-Learn
            git pull origin main
            echo "start"
            whoami
            npm install
            pm2 stop 1
            pm2 start 1
