name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x to Build
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: |
            npm install
            npm run build
      - name: Deploy on aws
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CI_KEY }}
          REMOTE_HOST: ${{ secrets.CI_HOST }}
          REMOTE_USER: ${{ secrets.CI_USERNAME }}
          ARGS: "-tt -i"
          SCRIPT: |
            echo "successfully connected"
          run: |
            cd "/home/ubuntu/project/CI-CD-Learn" || exit
            echo "INSIDE CI-CD-Learn"

            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
            . ~/.nvm/nvm.sh

            nvm install 18
            nvm use 18
            npm install -g pm2
            
            git pull origin main
            npm install
            npm run build

            echo "taken pull from main"
           
            pm2 stop ci-cd-learn
            pm2 start ci-cd-learn
            echo "server restarted"
