name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x to Build
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: |
            npm install
            npm run build
      - name: Deploy on aws
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CI_KEY }}
          REMOTE_HOST: ${{ secrets.CI_HOST }}
          REMOTE_USER: ${{ secrets.CI_USERNAME }}
          ARGS: "-tt -i"
          SCRIPT_BEFORE: |
            echo "successfully connected"
          run: cd "~/project/CI-CD-Learn/" || exit
            echo "INSIDE CI-CD-Learn"
          run: git pull origin main
          run: npm install
            echo "taken pull from main"
          run: pm2 restart 1
            echo "server restart"
