name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        run: |
          npm install
          npm run build
        
        env: 
          CI: true   

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
          script: |
              curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
              . ~/.nvm/nvm.sh

               nvm instal 18
               npm install -g pm2
               cd /home/ubuntu/project/CI-CD-Learn
               git pull origin main
               npm install
               npm run build
               pm2 restart api
            