name: deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x to Build
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: |
            npm install
            npm run build
      - name: Deploy on aws
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "build"
        run: |
            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
            . ~/.nvm/nvm.sh

             nvm install 18
             nvm use 18
             npm install -g pm2
             cd /home/ubuntu/project/CI-CD-Learn
             git pull origin main
             npm install
             npm run build
             pm2 restart ci-cd