name: deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          run: |
            npm install
            npm run build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: 127.0.0.1
          username: niraj-scaletech
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCmDXCqfuM1PWqIbLMwxe9W41p7cy5bvYwfUYQE4nszeuqFvygu8JkfKIb+56aPXlGQXqgp6GLS68aihANf8g4bfuknPeLLZD5Ip6PhLUNKIa3N/fb+4TIx9NKo0AoE3itKG8PCanZ5bL4Hl942e4kVL0+gmUhOT6gzwD9sNmOqMnNcmxTrYG+n8cmu7+uthEbfyiMfLMWCLXyhMRr/uzNkTsSf/nQBx+Ao7RCgauouBP6UlN01cxHyOw1dMh5Bv/BtEW95uaYBvFvqDIfAsGCIO6YJMMW9PyyDAV1xf97nFfAgmkb+mpI0UsNvuDQNJVlndoo1nh7eOhqLMHoymrhlu1bbeJqpKwj8jWr1YxmBuT04J6OV8vQcoUdDpfSuTzJ3QtL4HQln029qlseeAosBXGXRI1d5lMKtvf44h3VcE9MV2Xv0HGvCpUuEseKaYAUlts02jI0bLaxF/RIwFG7Y/Ux/S6VxBYbS4miOdzYbSh1bKzQ8GurSljpIL29IUzE9hIsJxQOzmn+U6aDWTgNVxaBb1SipD22GiYFA9JXNSMpsUjrHeaudWpGum4SUBV08j1aaccRjj0wLEPUHK1ltIk598AZqMhYakTfqL+ydeoEy+M5QGRPW3+NUH5HM55Cd35FEs7vzqgnuYmUDy4BbELR/3TJR8nkO0Xx6v28Ykw== niraj.visavadiya@scaletech.xyz
          port: 3000
          script: |
            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
            . ~/.nvm/nvm.sh

             nvm instal 18
             npm install -g pm2
             cd /home/ubuntu/project/CI-CD-Learn
             git pull origin main
             npm install
             npm run build
             pm2 restart ci-cd
